language: ruby
before_install:
  - sudo apt-get install libxml2-dev libxslt1-dev
rvm:
  - 2.1.9
  - 2.2.4
  - 2.3.1
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
script: rake test
